### ISSUE TITLE
Unsure whether variable assignment can reference variables

### ISSUE THREAD

**Issue by ngirard** [DanCardin/sauce#29]
After reading the documentation, I'm left unsure whether the following is possible:
```sh
sauce set env foo='${bar};foo'
```

**Comment by DanCardin** [comment]
I'm not entirely sure what this is supposed to do.

```
$ sauce set env bar=meow
$ sauce set env foo='${bar}'
$ sauce
$ env | grep foo
foo=meow
```
seems like the intent behind what you're doing above, but i'm not sure?

**Comment by DanCardin** [comment]
so tl;dr, i think the answer is yes, so I'm going to close this? happy to reopen if not
